$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: 
  local_path: ../src/
command: >
  python train.py --epochs 5 --data_path {inputs.training_data}
environment:
  docker:
    image: mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20210301.v1
  conda_file: file:../src/environment.yml
compute:
  target: azureml:cpu-cluster
inputs:
  training_data:
    mode: download
    data:
      local_path: ../data/
experiment_name: mnist-example
description: Train a RESNET-18 convolutional neural network (CNN) with fast.ai on the MNIST dataset